version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: quote_data
        target: /app/quote_data_outputs
      - type: volume
        source: mock_data
        target: /app/mock_data_outputs
      - type: bind
        source: /tmp/pulseaudio.socket
        target: /tmp/pulseaudio.socket
    environment:
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - BACKENDLESS_API_URL=${BACKENDLESS_API_URL}
      - BACKENDLESS_APP_ID=${BACKENDLESS_APP_ID}
      - BACKENDLESS_API_KEY=${BACKENDLESS_API_KEY}
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DOCKER_CONTAINER=true
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      - ALSA_CONFIG_PATH=/etc/asound.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  quote_data:
    driver: local
  mock_data:
    driver: local 